spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE:test}
      uri: ${MONGO_URI:mongodb://${DBUSER:root}:${DBPASS:E5press0}@localhost:27017/test}?authSource=admin&maxPoolSize=50&connectTimeoutMS=2000&serverSelectionTimeoutMS=2000
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /api

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
